### ISSUE TITLE
Scope for structs?

### ISSUE THREAD

**Issue by deresh-andrew** [ulex/ZenSharp#12]
I've looked trough source code and didn't found any "InCSharpStruct" or "InCSharpStructure" scope. I think it is not implemented. Please correct me if I'm wrong.
Thanks for awesome plugin =)

**Comment by ulex** [comment]
Hi, Andrew. Welcome to GitHub :+1: 
Thank for you'r feedback. I have added struct scope and publish version 1.1.2 in R# Gallery.
