### ISSUE TITLE
ReSharper 9.1 support

### ISSUE THREAD

**Issue by geirsagberg** [ulex/ZenSharp#13]
Hi, love your plugin! Would be nice if it worked with ReSharper 9.1 :)

**Comment by ulex** [comment]
Thanks. Already in R# gallery :smile:

**Comment by ulex** [comment]
btw, looks like JB using some kind of moderation in their R# gallery
So ZenSharp is not available in extension manager.
As workaround you can download [raw package](https://resharper-plugins.jetbrains.com/api/v2/package/Ulex.ZenSharp/1.2.0) and add custom extension source in R# settings.

**Comment by controlflow** [comment]
We don't use moderation, this is nuget automatically-curated feeds taking some time to update (looks quite unpredictable), I've just forced it to re-index and now ZenSharp is available in extension manager.

We will definitely do something about that issue, sorry :\

**Comment by geirsagberg** [comment]
Great stuff, now my productivity is back up to normal again :) Thanks for the quick response!

**Comment by ulex** [comment]
Cool, thanks!
