### ISSUE TITLE
Update README property examples

### ISSUE THREAD

**Issue by anjdreas** [ulex/ZenSharp#14]
The README currently states `pps` will generate `{ get; set; }` properties, but instead it generates `{ get; private set; }`.

After reading through the template here are the update examples:
`ppsA` for `public string A { get; private set; }`
`ppsA+` for `public string A { get; set; }`
`ppsA+p` for `public string A { get; protected set; }`

**Comment by anjdreas** [comment]
Awesome plugin by the way, I've been using mnemonics a lot and found it lacking on not being configurable and poor default shortcuts.

**Comment by ulex** [comment]
Thank you. I have updated the README.
