### ISSUE TITLE
Template for method with arguments

### ISSUE THREAD

**Issue by AOrlov** [ulex/ZenSharp#15]
Hi!

Last an hour I've been trying to manage with method template and seems that it doesn't work for me.
According to this template:
```
method ::= access ("virtual "=vm | "abstract "=am | "static "=M | ""=m) (type | "void") space identifier methodArgs methodBody
methodBody ::= " { " cursor " }"
methodArgs ::=  "(" (""="," arg)? ")"
arg ::= primType " " identifier2 
```

the shortcut for 
``` 
public string Foo(string param1)
``` 
should be like: 
``` 
pmsFoo(sparam1)
 ```
but when I typing such combination it gives me just:
```
public string Foo()
{
			
}
```

So, what I do in the wrong way?

**Comment by AOrlov** [comment]
Guys, is anybody here?

**Comment by ulex** [comment]
Hi. Sorry for long answer. 
Shortcut for  `public string Foo(string param1) { $END$ } ` is `pmFoo,sparam1`.

There's no documentation for it, but rules kind of `"juststring"` is always expand after pressing tab and has no affect on shortcut. On the other hand, rules like `"expand"="short"` mean that if you type `short` and press tab this rule will replace word `short` to `expand`.

So in rule `methodArgs ::=  "(" (""="," arg)? ")"` brackets is not used in shortcut and instead it you should type `,<type rule><identifier name>`

Btw, nice idea about split function name and argument with bracket. I will replace it soon.

**Comment by AOrlov** [comment]
Thank you, Alexander!
