### ISSUE TITLE
Usage for other languages

### ISSUE THREAD

**Issue by funivan** [ulex/ZenSharp#16]
Idea of this plugona is very cool. Can I use this plugin for other languages like php, Java, JavaScript etc..?

I create similar plugin for phpstorm with same idea but different realisation. https://github.com/FastCoddy/intellij-plugin/blob/master/docs/group-and-tabs.md

Now I'm tying to make it better and I find your plugin.

**Comment by ulex** [comment]
> Can I use this plugin for other languages like php, Java, JavaScript etc..?

Main idea of ZenSharp language is not bounded to specific language. But I don't know any easy way to create interoperable bridge via .net and java.

> Now I'm tying to make it better

IMO, what really lacked in your plugin is documentation. To figure out benefits I'm spent the whole 10 minutes.
