### ISSUE TITLE
xUnit Support?

### ISSUE THREAD

**Issue by Michael-DST** [ulex/ZenSharp#21]
Man this looks like a great project.  I learned about it after watching a R# webinar about it last Tuesday.  Do you have plans to support xUnit?  I am trying to wrap my head around how this all works, but this looks great!

**Comment by Michael-DST** [comment]
FWIW here is the webinar where ZenSharp was mentioned:
http://blog.jetbrains.com/dotnet/2015/12/09/continuous-testing-webinar-recording/

**Comment by ulex** [comment]
Support for xUnit is pretty easy. All you need is modify ZenSharp configuration (in ReSharper -> Edit ZenSharp templates). This file define all templates ZenSharp support and located in My Documents folder by default.
For example, Matt used this template in `InCSharpClass` scope.

    | ""=test "[NUnit.Framework.TestAttribute] public void Test" identifier "(){" cursor "}"

which is definition for single word `test` followed by optional name identifier will expanded by tab to:

        [Test]
        public void Identifier()
        {
            <Cursor>
        }

I have never used XUnit, but looks like all you need is replace definition to `Xunit.Fact`
Month ago I changed this template to 'new' method. see  d526d047f93fb0eb52b6c8d4a26ce25f3b46aa1b 

Thanks for the link :-)

**Comment by Michael-DST** [comment]
OK this is great!  I think I have enough here to get this figured out.  Thanks again. :)

**Comment by Michael-DST** [comment]
Awesome!  FYI, I got this working piece of cake (mmmm cake).  I am also using the R# extension [TestCop](http://testcop.codeplex.com) and now I can easily create a test class for any given class and then use ZenSharp for a quick test!  Soooooo nice!  FWIW, I am using "tt" (test template) for the template shortkey.  So very nice. :D

**Comment by Michael-DST** [comment]
Ah, spoke too soon. :)  I am looking into methods, and it appears that I cannot "end" in a method, or build out a method argument.  Is this a known issue?  In the readme.md it says that the $end$ for pamb is in the method signature, but it ends in the method body for me.
