### ISSUE TITLE
Support for Non-Standard/Custom Types

### ISSUE THREAD

**Issue by Michael-DST** [ulex/ZenSharp#22]
It would be nice to be able to use ZenSharp to create members that reference types outside of the basic types referenced in the readme.  I am not sure how you would do that, however. :)  But, it would be handy, as what I am doing now is using "o" for object, and then having to delete it and enter in my own type... hardly efficient. :/

**Comment by ulex** [comment]
Did you know about `t` macro? For example, type `pmtSomeName` and press tab.

**Comment by Michael-DST** [comment]
Dude.  I am fail!  That is awesome.  Super awesome extension and I am glad I watched that webinar. :)
