### ISSUE TITLE
pps+ does not work.

### ISSUE THREAD

**Issue by idealist1508** [ulex/ZenSharp#25]
![pps](https://cloud.githubusercontent.com/assets/4608274/15007095/5a3e6d84-11d6-11e6-8ca6-8621b32f4361.gif)
Depend it on some setting of Resharper ?

**Comment by ulex** [comment]
I can't reproduce it.
Could you please try to reset to default ReSharper settings in IntelliSence section (you can export it before to not lose it)
And which version of VS do you use?

**Comment by idealist1508** [comment]
Thank you for your tip. It depend on this setting:
![reoption](https://cloud.githubusercontent.com/assets/4608274/15014555/fb88a2e2-1206-11e6-9535-24b38ddf8dd6.PNG)

What do you mean? Is it possible to make some workaround here? Or should I make a bug report for ReSharper?

**Comment by ulex** [comment]
It's not a ReSharper bug, it's expected behavior.
I can suggest you change `+` in ZenSharp templates to something else (for example `P` mean public)
```diff
-propertySetAccessor ::= "protected "="+p" | ""="+" | "private "
+propertySetAccessor ::= "protected "="PR" | ""="P" | "private "
```
