### ISSUE TITLE
Doesn't work in ReSharper 2016.3 EAP 11 in VS2017

### ISSUE THREAD

**Issue by nms-plavoie** [ulex/ZenSharp#26]
ZenSharp doesn't work at all in VS2017 - ReSharper 2016.3 EAP 11. No menu, no intellisense.

I know, I'm early :P

**Comment by ulex** [comment]
Thank you @nms-plavoie. I have created issue in youtrack. Looks like this is integration problem with visual studio 2017 in ReSharper extension manager.
https://youtrack.jetbrains.com/issue/RSRP-462130

**Comment by ulex** [comment]
@nms-plavoie this is issue was resolved very quickly and already available in ReSharper 2016.3 EAP12

**Comment by nms-plavoie** [comment]
Yeah! Working again!
