### ISSUE TITLE
ReSharper 2016.3 is Released

### ISSUE THREAD

**Issue by Mike-EEE** [ulex/ZenSharp#27]
Looks like it's another refresh, which means it's time to hit up all my favorite extensions and ask them to create a supporting version. :)

I see your last checkin says "2016.3" in September, but I think that is for 2016.2, correct? In any case, [I have an issue on JetBrains' issue tracker to help simplify the whole extensions process](https://youtrack.jetbrains.com/issue/RSRP-459966).  Please take a moment to upvote the issue if you can.  Thank you for any support!

**Comment by ulex** [comment]
@Mike-EEE thank you for feedback 👍 
Actually september commit war really about support future version of 2016.3 (to support ZenSharp in 2016.3 EAP builds :) )
So ZenSharp already support 2016.3 RTM because no public API was changed.

**Comment by Mike-EEE** [comment]
Awesome!  Good to hear.  I wonder if other extensions are already 2016.3 compatible as well.  I guess I should stop being a chicken and find out. 😛
