### ISSUE TITLE
Resharper2018.2

### ISSUE THREAD

**Issue by LippyBoy** [ulex/ZenSharp#33]
Hi,
It's that time again - 
There is now a new version of resharper, and the plugin no longer supports it.

Is it possible to update it?

**Comment by ulex** [comment]
2d2188667d9c2844f57a55f01b6cf93007e34a96

**Comment by ulex** [comment]
@LippyBoy I have pushed it already. Are you able to see it from ReSharper extension manager?
The direct download link is https://resharper-plugins.jetbrains.com/api/v2/package/Ulex.ZenSharp/182.0.0.0

**Comment by LippyBoy** [comment]
Thank you.
I am behind a firewall and can't download it directly from r#, so I always download from here: https://resharper-plugins.jetbrains.com/packages/Ulex.ZenSharp/
