### ISSUE TITLE
Scopes: can I make templates for typescript?

### ISSUE THREAD

**Issue by Eonasdan** [ulex/ZenSharp#37]
Hello, thanks for your awesome plugin. I almost always wait to do R# upgrades till I make sure ZenTemplates is updated.

What are the available "scope"s? e.g. `scope "InCSharpStruct"`. It'd be nice if I could make templates in other context like tyescript where `ppsfoo` translated to `foo: string;` or whatever.

Thanks

**Comment by ulex** [comment]
@Eonasdan I've added scope based on language, you can try this build 
https://send.firefox.com/download/1f9ac8c81a9071ac/#Oc5tTsI1UXzOLqNyyZgmNw
with scope name `TYPE_SCRIPT`
I hope you will share your templates.

Thanks

**Comment by Eonasdan** [comment]
Cool. Maybe you could help me out with understand the syntax of the template.

I tried this for starters
```
access2 ::= (""=p | private=_) space
property2 ::= access2 identifier ":" space type ";"
scope "TYPE_SCRIPT" {
  start ::= property2
}
```

Unfortunately nothing new popup.

**Comment by ulex** [comment]
@Eonasdan sorry, it turns out my fix was not entirely correct. The scopes now works correctly (I have checked with your examples,  they are correct as well)
new build
https://send.firefox.com/download/8f4a69d27a5cfe08/#T6TpoJkyCjgy84zIhgRE4Q

**Comment by Falthazar** [comment]
Sorry to revive this, but I can't find in the code where it lists scopes? Is there one for XAML?

**Comment by ulex** [comment]
Any language supported by ReSharper is available as a scope. You can use
"XAML" for XAML

**Comment by Falthazar** [comment]
Awesome, thank you! I really shoulda figured that out though.. Sorry!

**Comment by plenartowicz** [comment]
Is there any list of available scopes?
