### ISSUE TITLE
2019.3

### ISSUE THREAD

**Issue by Eonasdan** [ulex/ZenSharp#38]
It's that time again. Can you please bump the supported version

**Comment by Mike-EEE** [comment]
PLEASSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE :) :) :)

**Comment by Mike-EEE** [comment]
Please feel free to vote for this issue to improve the extension model experience so we don't have to continually nag extension model authors for each release: https://youtrack.jetbrains.com/issue/RSRP-459966
