### ISSUE TITLE
Property with backing field

### ISSUE THREAD

**Issue by netcorefan1** [ulex/ZenSharp#39]
Hello,
this is by far the best R# plugin in the whole gallery and I must admit that I am sad to see that it doesn't have the attention it deserves. There should be repositories where people can submit their templates and most of all, a very accurate documentation because as is is very difficult to understand.

For example I tried for all the day to create a property with a backing field, but without success, something that with regular template I can do in a couple of minutes.
This is my code:
`propertyFull        ::= private _" identifier " ";" access ("abstract "=apf | "static "=Pf | "virtual "=vpf | ""=pf) type space identifier propertyFullBody cursor`

`propertyFullBody    ::= "{ get return _" identifier "; set _" identifier " = value; }"`

By pressing ppfsPropertyName (ppfs stands for "PublicPropertyFullstringTargetName) I should expect the following:
`private _PropertyName;`
 `public string PropertyName { get => _PropertyName; set => _PropertyName = value; }`

Unfortunately there's not even one thing that works. Any help??

There's also a very annoying bug that, from what I see, has been reported time ago, but has never  been completely fixed. Will open an issue for this.
Thanks

**Comment by ulex** [comment]
sorry again for delay with the response :(

ZenSharp is not as powerful as you would like. 
The core issue here is that it does not have any variables except special ones, which correspond to ReSharper live templates macros.
Provided example is not a valid C# code as it missing type for field declaration. If you specify it it means that input symbol `s` in alias language should expand to a "string" in two different position. And it is not possible to achieve currently, unfortunately.
You can replace `s` to macro expansion `suggType` (t) to fix that issue.
Second issue is that all rules are evaluating sequentially. `identifier` pattern come before `"abstract "=apf` in the definition, that means that the alias should be like `Nameapf`.

ps I feel you pain writing this template without auto-reload feature. Please let me know if it fixed for you or not in related ticket.
