### ISSUE TITLE
2020.2

### ISSUE THREAD

**Issue by OmiCron07** [ulex/ZenSharp#41]
New version, new build?

**Comment by Mike-E-angelo** [comment]
Out of 17 extensions that I use, this is the _only one_ that is not available for 2020.2.  I'm sort of shocked as I don't think I have ever had a problem with this one before.

---

Please vote to improve the extension model experience so we don't have to continually nag extension authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by Mike-E-angelo** [comment]
This is kind of a gutpunch as I use it more than any other extension by far.  I usually check this first to see if it's ready but since it always is, I skipped it.  Figures. :P

FWIW, mentioned here: https://youtrack.jetbrains.com/issue/RSRP-459966#focus=Comments-27-4373699.0-0

**Comment by ulex** [comment]
Mentioning in youtrack works 😂, still can't find a convenient way to work with github notifications, sorry for the delay with the updates.

>The plugin update is pending JetBrains approval
https://plugins.jetbrains.com/plugin/11645-zensharp-auto-completion-plugin

**Comment by Mike-E-angelo** [comment]
Awesome, thank you for your efforts and patience, @ulex!
