### ISSUE TITLE
Question: Include Namespace for Extension Methods?

### ISSUE THREAD

**Issue by Mike-E-angelo** [ulex/ZenSharp#43]
Is there a way to include namespaces for extension methods?  In my case, my template creates a default assertion from `FluentAssertions`, but its type is not defined, so it by default it is not valid:

![](https://i.imgur.com/4vcwMaA.png)

Types work easy and reliably enough, but I am unclear on how to do the same with an extension method.  Is this possible?

**Comment by ulex** [comment]
ZenSharp is based on ReSharper's templates, AFAIK there is not way to import namespace for an extension method.
I've found a related ticket in ReSharper's youtrack https://youtrack.jetbrains.com/issue/RSRP-330334

**Comment by Mike-E-angelo** [comment]
Thank you for your time and assistance, @ulex!  FWIW this is easily the most used R# plugin in my world. 👍
