### ISSUE TITLE
Scope for Record (C# 9)?

### ISSUE THREAD

**Issue by plenartowicz** [ulex/ZenSharp#44]
Hi, 
A new user data type 'record' was added in C# 9.
Is there a scope for it?

In default template file I've found scope for class and struct and interface so I've added similar scope for record but it doesn't work:
`scope "InCSharpRecord" {
  start ::= constructor | property
}`

**Comment by ISkomorokh** [comment]
@ulex are there any plans to support Records?

**Comment by ulex** [comment]
Fixed by @ZbynaM
