### ISSUE TITLE
C++ supports?

### ISSUE THREAD

**Issue by plenartowicz** [ulex/ZenSharp#48]
Hi,

I would like to use ZenSharp in C++ project but (of course) it doesn't work now. I thought the ReSharper C++ is required but that's not the problem (or I don't know how to "turn on" C++ supports).

Are there any plans to extend ZenSharp to (let's say) ZenCpp or is there any easy way to adjust the ZenSharp engine to support C++?

**Comment by ZbynaM** [comment]
Integration is closely tied to Resharpers CSharp API, that means there is no "turn on" C++ option. But i think it is possible, only depends on knowledge of Resharper API.
ZenSharps engine, the PEG parser can be used as is, but it is written in no longer supported language.

I don't know what the plans are.

**Comment by Falthazar** [comment]
> ZenSharps engine, the PEG parser can be used as is, but it is written in no longer supported language.

Want to try converting it to ANTLR (with ulex's permission of course)? I've thought about it but haven't had the time/motivation to do it.

**Comment by ulex** [comment]
@plenartowicz ZenSharp already works in C++ when ReSharper C++ is installed (as in any other language known by ReSharper). This feature was implemented as part of #37.
You can define your templates in section `CPP`.

> I don't know what the plans are.
> Want to try converting it to ANTLR 

@ZbynaM I don't have any plans to convert existing PEG parser on Nemerle. Yes it is based on outdated and not supported technology, but it works. And as you correctly mentioned, the core project is unaware of ReSharper's APIs, so it should be possible to reuse this code in other projects.

@Falthazar it would be highly appreciated if you convert it to any supported solution 😀 Be aware, that it is not enough to convert only the parser itself (which is only 174 lines long), it also forces to rewrite entire Core project to C#.
